
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author INDRAJITH
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int turn=2;
    int buttonUsed[]={0,0,0,0,0,0,0,0,0};
    int pXwon[]={0,0,0,0,0,0,0,0,0};
    int pOwon[]={0,0,0,0,0,0,0,0,0};

    int pXwon()
    {
        if(pXwon[0]==1 && pXwon[1]==1 && pXwon[2]==1)
        {
            return 1;  
        }
        if(pXwon[3]==1 && pXwon[4]==1 && pXwon[5]==1)
        {
            return 1;  
        }
        if(pXwon[6]==1 && pXwon[7]==1 && pXwon[8]==1)
        {
            return 1;  
        }
        if(pXwon[0]==1 && pXwon[3]==1 && pXwon[6]==1)
        {
            return 1;  
        }
        if(pXwon[1]==1 && pXwon[4]==1 && pXwon[7]==1)
        {
            return 1;  
        }
        if(pXwon[2]==1 && pXwon[5]==1 && pXwon[8]==1)
        {
            return 1;  
        }
        if(pXwon[0]==1 && pXwon[4]==1 && pXwon[8]==1)
        {
            return 1;  
        }
        if(pXwon[2]==1 && pXwon[4]==1 && pXwon[6]==1)
        {
            return 1;  
        }
return 0;
    }

    
       int pOwon()
    {
        if(pOwon[0]==1 && pOwon[1]==1 && pOwon[2]==1)
        {
            return 1;  
        }
        if(pOwon[3]==1 && pOwon[4]==1 && pOwon[5]==1)
        {
            return 1;  
        }
        if(pOwon[6]==1 && pOwon[7]==1 && pOwon[8]==1)
        {
            return 1;  
        }
        if(pOwon[0]==1 && pOwon[3]==1 && pOwon[6]==1)
        {
            return 1;  
        }
        if(pOwon[1]==1 && pOwon[4]==1 && pOwon[7]==1)
        {
            return 1;  
        }
        if(pOwon[2]==1 && pOwon[5]==1 && pOwon[8]==1)
        {
            return 1;  
        }
        if(pOwon[0]==1 && pOwon[4]==1 && pOwon[8]==1)
        {
            return 1;  
        }
        if(pOwon[2]==1 && pOwon[4]==1 && pOwon[6]==1)
        {
            return 1;  
        }
return 0;
    }
    
    public NewJFrame() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        b0 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        again = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        again.setBackground(new java.awt.Color(51, 255, 0));
        again.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        again.setText("PLAY AGAIN");
        again.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("PLAY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(again))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(again)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        if(buttonUsed[0]==0)
        {
        if(turn%2==0)
        {
            b0.setText("X");
            turn++;
            buttonUsed[0]=1;
            pXwon[0]=1;
           // b0.setColor(Color.yellow);
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
        }
        else 
        {
            b0.setText("O");
            turn--;
             buttonUsed[0]=1;
             pOwon[0]=1;
             
              int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
             
             
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button is Used !!!");
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         if(buttonUsed[2]==0)
        {
        if(turn%2==0)
        {
            b2.setText("X");
            turn++;
            buttonUsed[2]=1;
            pXwon[2]=1;
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
        }
        else 
        {
            b2.setText("O");
            turn--;
             buttonUsed[2]=1;
             pOwon[2]=1;
             
              int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
             
             
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button is Used !!!");
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        
         if(buttonUsed[1]==0)
        {
        if(turn%2==0)
        {
            b1.setText("X");
            turn++;
            buttonUsed[1]=1;
            pXwon[1]=1;
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
        }
        else 
        {
            b1.setText("O");
            turn--;
             buttonUsed[1]=1;
             pOwon[1]=1;
             
              int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
             
             
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button is Used !!!");
        }
        
        
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        
         if(buttonUsed[4]==0)
        {
        if(turn%2==0)
        {
            b4.setText("X");
            turn++;
            buttonUsed[4]=1;
            pXwon[4]=1;
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
        }
        else 
        {
            b4.setText("O");
            turn--;
             buttonUsed[4]=1;
             pOwon[4]=1;
             
              int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
             
             
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button is Used !!!");
        }
        
        
        
    }//GEN-LAST:event_b4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
         if(buttonUsed[3]==0)
        {
        if(turn%2==0)
        {
            b3.setText("X");
            turn++;
            buttonUsed[3]=1;
            pXwon[3]=1;
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
        }
        else 
        {
            b3.setText("O");
            turn--;
             buttonUsed[3]=1;
             pOwon[3]=1;
             
              int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
             
             
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button is Used !!!");
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
         if(buttonUsed[6]==0)
        {
        if(turn%2==0)
        {
            b6.setText("X");
            turn++;
            buttonUsed[6]=1;
            pXwon[6]=1;
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
        }
        else 
        {
            b6.setText("O");
            turn--;
             buttonUsed[6]=1;
             pOwon[6]=1;
             
              int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
             
             
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button is Used !!!");
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
         if(buttonUsed[7]==0)
        {
        if(turn%2==0)
        {
            b7.setText("X");
            turn++;
            buttonUsed[7]=1;
            pXwon[7]=1;
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
        }
        else 
        {
            b7.setText("O");
            turn--;
             buttonUsed[7]=1;
             pOwon[7]=1;
             
              int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
             
             
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button is Used !!!");
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        
         if(buttonUsed[5]==0)
        {
        if(turn%2==0)
        {
            b5.setText("X");
            turn++;
            buttonUsed[5]=1;
            pXwon[5]=1;
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
        }
        else 
        {
            b5.setText("O");
            turn--;
             buttonUsed[5]=1;
             pOwon[5]=1;
             
              int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
             
             
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button is Used !!!");
        }
        
        
        
    }//GEN-LAST:event_b5ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
         if(buttonUsed[8]==0)
        {
        if(turn%2==0)
        {
            b8.setText("X");
            turn++;
            buttonUsed[8]=1;
            pXwon[8]=1;
            int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
        }
        else 
        {
            b8.setText("O");
            turn--;
             buttonUsed[8]=1;
             pOwon[8]=1;
             
              int result1=pXwon();
            int result2=pOwon();
            if(result1==1)
            {
                JOptionPane.showMessageDialog(rootPane,"Player X won the game");
            }
            else if(result2==1)
            {
                 JOptionPane.showMessageDialog(rootPane,"Player O won the game");
            }
             
             
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"This Button is Used !!!");
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void againActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againActionPerformed
        // TODO add your handling code here:
        b0.setText("");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        
        turn=2;
        for(int i=0;i<9;i++)
        {
            buttonUsed[i]=0;
                    pXwon[i]=0;
                    pOwon[i]=0;
        }
        
        
        
    }//GEN-LAST:event_againActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton again;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
